---
- name: Install Apache
  hosts: all
  become: yes
  tasks:
  - name: Install Apache
    ansible.builtin.package:
     name: apache2
     state: present
  - name: copy html
    ansible.builtin.copy:
     src: index.html
     dest: /var/www/html/
